# Generated by Django 2.2.1 on 2019-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('date_joined', models.DateField()),
                ('id_number', models.SmallIntegerField()),
            ],
        ),
    ]
