# Generated by Django 2.2.1 on 2019-05-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190530_0035'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
