# Generated by Django 2.2.1 on 2019-09-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190723_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
