# Generated by Django 2.2.1 on 2019-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20190917_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Courses',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
